name: Gradle Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Instala Google Chrome y ChromeDriver
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

          # Obtener la versión de Google Chrome
          CHROME_VERSION=$(google-chrome --version | grep -o '[0-9]*\.[0-9]*\.[0-9]*')
          echo "Chrome version: $CHROME_VERSION"

          # Obtener la versión principal de Chrome
          CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f 1)
          echo "Chrome major version: $CHROME_MAJOR_VERSION"

          # Asignar manualmente la versión de ChromeDriver
          CHROMEDRIVER_VERSION="130.0.6723.63"  # Cambia a la versión específica de ChromeDriver

          # Imprimir la versión de ChromeDriver
          echo "ChromeDriver version: $CHROMEDRIVER_VERSION"

          # Descargar y descomprimir ChromeDriver
          wget https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.58/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip

          # Mover el archivo chromedriver a /usr/local/bin/ y darle permisos de ejecución
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver


      # 3. Configura JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      # 4. Configura Gradle
      - name: Setup Gradle
        uses: gradle/wrapper-validation-action@v1
        with:
          gradle-version: '8.8'

      # 5. Asegura que gradlew tenga permisos de ejecución
      - name: Give Gradlew Execution Permissions
        run: chmod +x gradlew

      # 6. Compila el proyecto con Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # 7. Publica en GitHub Packages
      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
